-- MySQL Script generated by MySQL Workbench
-- Wed Aug 26 17:53:36 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema libreria_sofia
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema libreria_sofia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `libreria_sofia` DEFAULT CHARACTER SET utf8 ;
USE `libreria_sofia` ;

-- -----------------------------------------------------
-- Table `libreria_sofia`.`autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`autor` (
  `id_autor` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellido` VARCHAR(80) NOT NULL,
  `fecha_nacimiento` DATE NULL DEFAULT NULL,
  `nacionalidad` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_autor`),
  UNIQUE INDEX `uq_autor` (`nombre` ASC, `apellido` ASC, `fecha_nacimiento` ASC) VISIBLE,
  INDEX `ix_autor_apellido` (`apellido` ASC, `nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`editorial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`editorial` (
  `id_editorial` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(120) NOT NULL,
  `pais` VARCHAR(60) NULL DEFAULT NULL,
  PRIMARY KEY (`id_editorial`),
  UNIQUE INDEX `uq_editorial_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`categoria` (
  `id_categoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `descripcion` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `uq_categoria_nombre` (`nombre` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`libro` (
  `id_libro` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `isbn` CHAR(13) NOT NULL,
  `titulo` VARCHAR(200) NOT NULL,
  `id_editorial` INT UNSIGNED NOT NULL,
  `id_categoria` INT UNSIGNED NOT NULL,
  `fecha_publicacion` DATE NULL DEFAULT NULL,
  `precio` DECIMAL(10,2) NOT NULL,
  `stock` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`id_libro`),
  UNIQUE INDEX `uq_libro_isbn` (`isbn` ASC) VISIBLE,
  INDEX `ix_libro_titulo` (`titulo` ASC) VISIBLE,
  INDEX `ix_libro_categoria` (`id_categoria` ASC) VISIBLE,
  INDEX `ix_libro_editorial` (`id_editorial` ASC) VISIBLE,
  FULLTEXT INDEX `ftx_libro_titulo` (`titulo`) VISIBLE,
  CONSTRAINT `fk_libro_categoria`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `libreria_sofia`.`categoria` (`id_categoria`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_libro_editorial`
    FOREIGN KEY (`id_editorial`)
    REFERENCES `libreria_sofia`.`editorial` (`id_editorial`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`libro_autor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`libro_autor` (
  `id_libro` INT UNSIGNED NOT NULL,
  `id_autor` INT UNSIGNED NOT NULL,
  `orden` TINYINT UNSIGNED NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_libro`, `id_autor`),
  INDEX `ix_la_autor` (`id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_la_autor`
    FOREIGN KEY (`id_autor`)
    REFERENCES `libreria_sofia`.`autor` (`id_autor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_la_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `libreria_sofia`.`libro` (`id_libro`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`cliente` (
  `id_cliente` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(80) NOT NULL,
  `apellido` VARCHAR(80) NOT NULL,
  `email` VARCHAR(150) NOT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `fecha_registro` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_cliente`),
  UNIQUE INDEX `uq_cliente_email` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`direccion` (
  `id_direccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `calle` VARCHAR(150) NOT NULL,
  `ciudad` VARCHAR(80) NOT NULL,
  `estado` VARCHAR(80) NULL DEFAULT NULL,
  `codigo_postal` VARCHAR(15) NULL DEFAULT NULL,
  `pais` VARCHAR(60) NOT NULL,
  `es_principal` TINYINT(1) NOT NULL DEFAULT '1',
  PRIMARY KEY (`id_direccion`),
  INDEX `ix_direccion_cliente` (`id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_direccion_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `libreria_sofia`.`cliente` (`id_cliente`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`pedido` (
  `id_pedido` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_cliente` INT UNSIGNED NOT NULL,
  `id_direccion` INT UNSIGNED NULL DEFAULT NULL,
  `fecha_compra` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado` ENUM('pendiente','procesado','completado','cancelado') NOT NULL DEFAULT 'pendiente',
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_direccion` (`id_direccion` ASC) VISIBLE,
  INDEX `ix_pedido_cliente` (`id_cliente` ASC, `fecha_compra` ASC) VISIBLE,
  INDEX `ix_pedido_estado` (`estado` ASC) VISIBLE,
  CONSTRAINT `fk_pedido_cliente`
    FOREIGN KEY (`id_cliente`)
    REFERENCES `libreria_sofia`.`cliente` (`id_cliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pedido_direccion`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `libreria_sofia`.`direccion` (`id_direccion`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`detalle_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`detalle_pedido` (
  `id_pedido` INT UNSIGNED NOT NULL,
  `id_libro` INT UNSIGNED NOT NULL,
  `cantidad` INT UNSIGNED NOT NULL,
  `precio_unitario` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_pedido`, `id_libro`),
  INDEX `ix_detalle_libro` (`id_libro` ASC) VISIBLE,
  CONSTRAINT `fk_detalle_libro`
    FOREIGN KEY (`id_libro`)
    REFERENCES `libreria_sofia`.`libro` (`id_libro`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_detalle_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `libreria_sofia`.`pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `libreria_sofia`.`transaccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `libreria_sofia`.`transaccion` (
  `id_transaccion` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `id_pedido` INT UNSIGNED NOT NULL,
  `metodo_pago` ENUM('tarjeta_credito','tarjeta_debito','paypal','transferencia','efectivo') NOT NULL,
  `monto_total` DECIMAL(12,2) NOT NULL,
  `fecha_transaccion` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `estado_pago` ENUM('autorizada','rechazada','reembolsada') NOT NULL DEFAULT 'autorizada',
  `referencia_externa` VARCHAR(80) NULL DEFAULT NULL,
  PRIMARY KEY (`id_transaccion`),
  UNIQUE INDEX `uq_transaccion_pedido` (`id_pedido` ASC) VISIBLE,
  CONSTRAINT `fk_transaccion_pedido`
    FOREIGN KEY (`id_pedido`)
    REFERENCES `libreria_sofia`.`pedido` (`id_pedido`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
